# Created using wingetcreate 1.5.2.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.5.0.schema.json

PackageIdentifier: RomexSoftware.PrimoCache
PackageVersion: 4.3.0
PackageLocale: en-US
Publisher: Romex Software
PackageName: PrimoCache
License: Copyright 2008-2023 Romex Software. All rights reserved.
Copyright: Copyright© Romex Software
ShortDescription: Excellent Software Caching Solution to Accelerate Storage.
ManifestType: defaultLocale
ManifestVersion: 1.5.0
