# Created using wingetcreate 1.5.2.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: RomexSoftware.PrimoCache
PackageVersion: 4.3.0
Platform:
- Windows.Desktop
InstallerType: inno
Scope: machine
InstallModes:
- verysilent
UpgradeBehavior: install
Installers:
- Architecture: x86
  InstallerUrl: https://static.romexsoftware.com/download/primo-cache/PrimoCache_Setup_4.3.0.exe
  InstallerSha256: 9225E04C41D47F8B5BEA6B23A246F2FF6702D560830E8DA9539695EFB603A50E
ManifestType: installer
ManifestVersion: 1.5.0
